services:
  connector:
    build:
      context: .
      dockerfile: dev.Dockerfile
    user: "${RUN_AS}"
    environment:
      HOME: "/app"
      DEPLOYMENT: "local"
      # S3 Configuration for local Minio
      S3_ENDPOINT_URL: "http://minio:9000"
      S3_PUBLIC_ENDPOINT_URL: "http://localhost:9003"
      S3_BUCKET: "testbucket"
      S3_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "minioadmin"
      AWS_SECRET_ACCESS_KEY: "minioadmin"
      SIGNED_LINK_EXPIRATION: "3600"
    env_file:
      - path: .env
        required: false
    ports:
      - 8200:8200/tcp
    volumes:
      - .:/app

  minio:
    container_name: "minio-spiffworkflow-connector"
    image: minio/minio
    command: server /data --console-address ":9004"
    ports:
      - "9003:9000" # S3 API
      - "9004:9002" # Minio Console
    volumes:
      - "./minio_data:/data"

  createbuckets:
    image: minio/minio
    depends_on:
      - minio
    restart: "no"
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/testbucket;
      /usr/bin/mc admin accesskey create myminio/ --access-key minioadmin_key --secret-key minioadmin_secret;
      exit 0;"
